# Generated by Django 4.2.1 on 2023-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_delete_userroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maker',
            field=models.BooleanField(default=False),
        ),
    ]
