# Generated by Django 4.2.1 on 2023-05-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maker',
        ),
    ]
