# Generated by Django 4.2.1 on 2023-05-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agreement_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
